baseURL = "https://kt-lab.tw/"
languageCode = "zh-tw"
title = "KT Lab 身心實驗室"
theme = "mainroad"
canonifyURLs = true

[pagination]
  pagerSize = 5

[outputs]
  home = ["HTML", "RSS", "JSON"]

[outputFormats.RSS]
  mediaType = "application/rss+xml"
  baseName = "rss"

[Params]
  subtitle = "瑜伽 靜坐 覺知 身心諮詢 一對一私人課"
  post_meta = ["date", "categories"]
  pager = true
  
[Params.sidebar]
  home = "right"
  list = "right"
  single = "right"
  widgets = ["search", "mailchimp", "categories", "tagcloud", "archives"]

[[menus.main]]
  name = "課程"
  url = "/schedule/"
  weight = 1

[[menus.main]]
  name = "位置"
  url = "/contact/"
  weight = 2

[[menus.main]]
  name = "關於 / about"
  url = "/about/"
  weight = 3

[markup.goldmark.renderer]
  unsafe = true
  hardWraps = true